# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d552656febeed89f69e5f475127ecefa4efc41a7e37ded8ab78ca43565a36d3720efd15233873a6973e0597d64ab57bd17cbe2f46db7d0ba49df064c972af6aa

test:
  secret_key_base: 189efb91294a13cd605ec39f530326d85a3998a9735c65155c6eb3f14f0d604714d85be498e5bc2288798dc1673f7c1f90f4530ca996df11bd43dbb7bfab2c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
